view: superstore_en {
  sql_table_name: `proj-terence-01.superstore_01.superstore_en` ;;

  dimension: row_id {
    hidden: yes
    primary_key: yes
    type: number
    sql: ${TABLE}.`Row ID` ;;
  }

  set: detail {
    fields: [
      order_id,
      order_date,
      customer_name,
      segment,
      product_name,
      category,
      subcategory,
      sales,
      profit,
      quantity
    ]
  }

  dimension: category {
    label: "Product Category"
    group_label: "Product"
    description: "High-level product category sold in the order."
    type: string
    sql: ${TABLE}.Category ;;
    synonyms: ["product category", "merchandise category", "department", "商品类别", "产品大类"]
  }
  dimension: city {
    label: "City"
    group_label: "Geography"
    description: "Customer city."
    type: string
    sql: ${TABLE}.City ;;
    synonyms: ["customer city", "location city", "城市"]
  }
  dimension: country_region {
    label: "Country or Region"
    group_label: "Geography"
    description: "Customer country or region."
    type: string
    map_layer_name: countries
    sql: ${TABLE}.Country_Region ;;
    synonyms: ["country", "region country", "market", "国家", "地区"]
  }
  dimension: customer_id {
    label: "Customer ID"
    group_label: "Customer"
    description: "Unique customer identifier from the Superstore source."
    type: string
    sql: ${TABLE}.`Customer ID` ;;
    synonyms: ["client id", "buyer id", "customer key", "客户编号"]
  }
  dimension: customer_name {
    label: "Customer Name"
    group_label: "Customer"
    description: "Customer or account name."
    type: string
    sql: ${TABLE}.`Customer Name` ;;
    synonyms: ["account", "account name", "buyer", "client", "客户", "客户名称"]
  }
  measure: discount {
    label: "Average Discount"
    group_label: "Discount"
    description: "Average discount rate across order lines."
    type: average
    sql: ${TABLE}.Discount ;;
    value_format_name: percent_1
    synonyms: ["avg discount", "discount rate", "markdown", "折扣率", "平均折扣"]
  }
  dimension_group: order {
    label: "Order"
    group_label: "Order Dates"
    description: "Date when the order was placed."
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.`Order Date` ;;
    synonyms: ["order date", "booking date", "sales date", "transaction date", "下单日期", "订单日期"]
  }
  dimension: order_id {
    label: "Order ID"
    group_label: "Order"
    description: "Unique order identifier."
    type: string
    sql: ${TABLE}.`Order ID` ;;
    synonyms: ["order number", "transaction id", "purchase id", "订单号"]
  }
  dimension: postal_code {
    hidden: yes
    type: number
    sql: ${TABLE}.`Postal Code` ;;
  }
  dimension: product_id {
    label: "Product ID"
    group_label: "Product"
    description: "Unique product identifier."
    type: string
    sql: ${TABLE}.`Product ID` ;;
    synonyms: ["sku", "item id", "product key", "产品编号"]
  }
  dimension: product_name {
    label: "Product Name"
    group_label: "Product"
    description: "Product name sold in the order."
    type: string
    sql: ${TABLE}.`Product Name` ;;
    synonyms: ["item", "sku name", "merchandise", "product", "产品", "商品"]
  }
  measure: profit {
    label: "Profit"
    group_label: "Financial Metrics"
    description: "Total profit generated by selected orders."
    type: sum
    sql: ${TABLE}.Profit ;;
    value_format: "$0.0,,\"M\""
    drill_fields: [detail*]
    synonyms: ["gross profit", "margin dollars", "earnings", "利润", "毛利"]
  }
  measure: quantity {
    label: "Units Sold"
    group_label: "Order Metrics"
    description: "Total quantity of products sold."
    type: sum
    sql: ${TABLE}.Quantity ;;
    value_format_name: decimal_0
    synonyms: ["units", "items sold", "volume", "销量", "件数"]
  }
  dimension: region {
    label: "Sales Region"
    group_label: "Geography"
    description: "Sales region used for performance analysis."
    type: string
    sql: ${TABLE}.Region ;;
    synonyms: ["territory", "area", "sales territory", "大区", "销售区域"]
  }
  measure: sales {
    label: "Sales"
    group_label: "Financial Metrics"
    description: "Total sales revenue before profit and discount analysis."
    type: sum
    sql: ${TABLE}.Sales ;;
    value_format: "$0.0,,\"M\""
    drill_fields: [detail*]
    synonyms: ["revenue", "gross sales", "GMV", "turnover", "销售额", "收入"]
  }
  dimension: segment {
    label: "Customer Segment"
    group_label: "Customer"
    description: "Customer segment such as Consumer, Corporate, or Home Office."
    type: string
    sql: ${TABLE}.Segment ;;
    synonyms: ["customer segment", "buyer segment", "client type", "客户细分", "客群"]
  }
  dimension_group: ship {
    label: "Ship"
    group_label: "Order Dates"
    description: "Date when the order was shipped."
    type: time
    timeframes: [raw, date, week, month, quarter, year]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.`Ship Date` ;;
    synonyms: ["ship date", "shipping date", "fulfillment date", "发货日期"]
  }
  dimension: ship_mode {
    label: "Ship Mode"
    group_label: "Shipping"
    description: "Shipping service level used for the order."
    type: string
    sql: ${TABLE}.`Ship Mode` ;;
    synonyms: ["delivery mode", "shipping method", "fulfillment method", "物流方式", "配送方式"]
  }
  dimension: state {
    label: "State"
    group_label: "Geography"
    description: "Customer state or province."
    type: string
    map_layer_name: us_states
    sql: ${TABLE}.State ;;
    synonyms: ["province", "state province", "州", "省份"]
  }
  dimension: subcategory {
    label: "Product Subcategory"
    group_label: "Product"
    description: "Detailed product subcategory."
    type: string
    sql: ${TABLE}.`Sub-Category` ;;
    synonyms: ["sub category", "product family", "item category", "产品小类", "商品子类"]
  }
  measure: count {
    label: "Line Count"
    group_label: "Order Metrics"
    description: "Number of order lines."
    type: count
    drill_fields: [product_name, customer_name]
    synonyms: ["rows", "line items", "record count", "明细行数"]
  }

  measure: order_count {
    label: "Order Count"
    group_label: "Order Metrics"
    description: "Distinct number of customer orders."
    type: count_distinct
    sql: ${order_id} ;;
    drill_fields: [detail*]
    synonyms: ["orders", "number of orders", "transactions", "订单数"]
  }

  measure: customer_count {
    label: "Customer Count"
    group_label: "Customer"
    description: "Distinct number of customers."
    type: count_distinct
    sql: ${customer_id} ;;
    drill_fields: [customer_name, segment, region]
    synonyms: ["unique customers", "accounts", "buyers", "客户数"]
  }

  measure: product_count {
    label: "Product Count"
    group_label: "Product"
    description: "Distinct number of products sold."
    type: count_distinct
    sql: ${product_id} ;;
    drill_fields: [product_name, category, subcategory]
    synonyms: ["unique products", "sku count", "items", "产品数"]
  }

  measure: average_order_value {
    label: "Average Order Value"
    group_label: "Financial Metrics"
    description: "Average sales revenue per distinct order."
    type: number
    sql: ${sales} / NULLIF(${order_count}, 0) ;;
    value_format: "$#,##0"
    synonyms: ["AOV", "average basket", "sales per order", "客单价", "平均订单金额"]
  }

  measure: profit_margin {
    label: "Profit Margin"
    group_label: "Financial Metrics"
    description: "Profit divided by sales. Use this for margin percentage questions."
    type: number
    sql: ${profit} / NULLIF(${sales}, 0) ;;
    value_format_name: percent_1
    synonyms: ["margin", "gross margin", "profit rate", "利润率", "毛利率"]
  }

  measure: sales_per_customer {
    label: "Sales per Customer"
    group_label: "Customer"
    description: "Average sales revenue per distinct customer."
    type: number
    sql: ${sales} / NULLIF(${customer_count}, 0) ;;
    value_format: "$#,##0"
    synonyms: ["revenue per customer", "customer value", "ARPC", "人均收入", "客均销售额"]
  }

  measure: discount_amount {
    label: "Estimated Discount Amount"
    group_label: "Discount"
    description: "Estimated sales amount discounted, calculated from sales multiplied by discount rate at the row level."
    type: sum
    sql: ${TABLE}.Sales * ${TABLE}.Discount ;;
    value_format: "$0.0,,\"M\""
    synonyms: ["discount dollars", "markdown amount", "discount value", "折扣金额"]
  }

  dimension: profit_status {
    label: "Profit Status"
    group_label: "Financial Metrics"
    description: "Classifies order lines into profitable, breakeven, or loss-making lines."
    type: string
    sql:
      CASE
        WHEN ${TABLE}.Profit > 0 THEN 'Profitable'
        WHEN ${TABLE}.Profit = 0 THEN 'Breakeven'
        ELSE 'Loss-Making'
      END ;;
    synonyms: ["loss status", "profitability status", "亏损状态", "盈利状态"]
  }

  dimension: discount_tier {
    label: "Discount Tier"
    group_label: "Discount"
    description: "Classifies order lines by discount intensity for pricing and margin analysis."
    type: string
    sql:
      CASE
        WHEN ${TABLE}.Discount >= 0.30 THEN 'High Discount'
        WHEN ${TABLE}.Discount >= 0.10 THEN 'Medium Discount'
        WHEN ${TABLE}.Discount > 0 THEN 'Low Discount'
        ELSE 'No Discount'
      END ;;
    synonyms: ["discount band", "markdown tier", "折扣等级", "折扣分层"]
  }

  measure: loss_amount {
    label: "Loss Amount"
    group_label: "Financial Metrics"
    description: "Positive amount of profit lost on loss-making order lines."
    type: sum
    sql: CASE WHEN ${TABLE}.Profit < 0 THEN -${TABLE}.Profit ELSE 0 END ;;
    value_format: "$0.0,,\"M\""
    synonyms: ["profit loss", "negative profit amount", "亏损金额"]
  }

  measure: loss_line_count {
    label: "Loss Line Count"
    group_label: "Financial Metrics"
    description: "Number of order lines with negative profit."
    type: sum
    sql: CASE WHEN ${TABLE}.Profit < 0 THEN 1 ELSE 0 END ;;
    value_format_name: decimal_0
    synonyms: ["loss-making rows", "negative profit lines", "亏损明细数"]
  }

  measure: high_discount_sales {
    label: "High Discount Sales"
    group_label: "Discount"
    description: "Sales revenue from order lines with discount of 30% or higher."
    type: sum
    sql: CASE WHEN ${TABLE}.Discount >= 0.30 THEN ${TABLE}.Sales ELSE 0 END ;;
    value_format: "$0.0,,\"M\""
    synonyms: ["sales under high discount", "high markdown sales", "高折扣销售额"]
  }

  measure: discount_to_sales_ratio {
    label: "Discount to Sales Ratio"
    group_label: "Discount"
    description: "Estimated discount amount divided by total sales."
    type: number
    sql: ${discount_amount} / NULLIF(${sales}, 0) ;;
    value_format_name: percent_1
    synonyms: ["discount ratio", "discount burden", "折扣销售占比"]
  }

  measure: profit_per_order {
    label: "Profit per Order"
    group_label: "Financial Metrics"
    description: "Average profit generated per distinct order."
    type: number
    sql: ${profit} / NULLIF(${order_count}, 0) ;;
    value_format: "$#,##0"
    synonyms: ["profit per transaction", "order profitability", "单均利润"]
  }

  measure: units_per_order {
    label: "Units per Order"
    group_label: "Order Metrics"
    description: "Average units sold per distinct order."
    type: number
    sql: ${quantity} / NULLIF(${order_count}, 0) ;;
    value_format_name: decimal_1
    synonyms: ["items per order", "basket size", "单均件数"]
  }

  measure: sales_last_year {
    label: "Sales Last Year"
    group_label: "Period over Period"
    description: "Sales from the comparable period in the previous year."
    type: period_over_period
    based_on: superstore_en.sales
    based_on_time: superstore_en.order_year
    period: year
    kind: previous
    value_format: "$0.0,,\"M\""
    synonyms: ["revenue last year", "previous year sales", "去年销售额", "去年收入"]
  }

  measure: sales_yoy_difference {
    label: "Sales YoY Difference"
    group_label: "Period over Period"
    description: "Sales difference between the selected period and the comparable period in the previous year."
    type: period_over_period
    based_on: superstore_en.sales
    based_on_time: superstore_en.order_year
    period: year
    kind: difference
    value_format: "$0.0,,\"M\""
    synonyms: ["year over year sales change", "revenue change vs last year", "同比销售额变化"]
  }

  measure: sales_yoy_growth {
    label: "Sales YoY Growth"
    group_label: "Period over Period"
    description: "Relative sales growth versus the comparable period in the previous year."
    type: period_over_period
    based_on: superstore_en.sales
    based_on_time: superstore_en.order_year
    period: year
    kind: relative_change
    value_format_name: percent_1
    synonyms: ["YoY growth", "year over year growth", "revenue growth", "同比增长"]
  }

  measure: profit_last_year {
    label: "Profit Last Year"
    group_label: "Period over Period"
    description: "Profit from the comparable period in the previous year."
    type: period_over_period
    based_on: superstore_en.profit
    based_on_time: superstore_en.order_year
    period: year
    kind: previous
    value_format: "$0.0,,\"M\""
    synonyms: ["last year profit", "previous year profit", "去年利润"]
  }

  measure: profit_yoy_growth {
    label: "Profit YoY Growth"
    group_label: "Period over Period"
    description: "Relative profit growth versus the comparable period in the previous year."
    type: period_over_period
    based_on: superstore_en.profit
    based_on_time: superstore_en.order_year
    period: year
    kind: relative_change
    value_format_name: percent_1
    synonyms: ["profit growth", "profit year over year", "利润同比增长"]
  }

  measure: sales_last_month {
    label: "Sales Last Month"
    group_label: "Period over Period"
    description: "Sales from the previous month."
    type: period_over_period
    based_on: superstore_en.sales
    based_on_time: superstore_en.order_month
    period: month
    kind: previous
    value_format_name: usd
    synonyms: ["previous month sales", "last month revenue", "上月销售额"]
  }

  measure: sales_mom_growth {
    label: "Sales MoM Growth"
    group_label: "Period over Period"
    description: "Relative sales growth versus the previous month."
    type: period_over_period
    based_on: superstore_en.sales
    based_on_time: superstore_en.order_month
    period: month
    kind: relative_change
    value_format_name: percent_1
    synonyms: ["month over month growth", "MoM growth", "环比增长"]
  }
}
